### ISSUE TITLE
Epic: Requirements; Entitlement Phase 2: separate out product from feature on auth service

### ISSUE THREAD

**Issue by altsang** [strongloop/strong-arc#1222]
As a SL sales manager, I would want to provide the explicit ability to specify license keys for individual products and individual features so that we can have better resolution on measuring usage and intent.

- [ ] auth service changes
- [ ] Arc logic changes for renewal
- [ ] Arc licensing page UX for requesting features and products
- [x] licensing wrapper API interface to check not just product but individual feature

**Comment by ijroth** [comment]
Just pointing out that at this time we don't have the need for feature-level licensing.

It would be nice to know who is using the connectors and tie that to our intelligence on Arc.

**Comment by altsang** [comment]
@ijroth - this is for entitlement phase 2 - do not want to do this for phase 2?
if we don't, then a feature will expire, we will ask for renewal - at the product level -it might be possible to pass along what  actually expired and pass that info to segment.io but that's work as well

example)

product - connectors
feature - mssql connector, 3/4/2014, 5/4/2014 - expires

renewal logic in Arc will ask to renew connectors, we can try to pass along mssql connector expired

will that work?

**Comment by ijroth** [comment]
My misunderstanding, I didn't realize what features meant. Al explained it to me.

**Comment by chandadharap** [comment]
@raymond Please get together with @altsang  on approach for data structure and database migration. @raymond I'd like you to create eng stories that break this up and estimate before I move into Sprint.

**Comment by chandadharap** [comment]
@altsang This is an epic level story and needs breaking down, I'll do  that.

**Comment by altsang** [comment]
we discussed with @anthonyettinger this afternoon, @raymondfeng putting together a dev blog plan

**Comment by chandadharap** [comment]
I'd rather call this a Spike with output in Spikes. This will never officially make it into a dev blog. The concept of dev blog has shifted recently in Eng.. Same principle but in the Spike area of the wiki.

**Comment by altsang** [comment]
i'm fine with whatever you want to call it.  I think when she "spike" on a feature or task, that one of the deliverables is a blog spec/dev blog/Google doc ((whatever you want to call it too))  - something that can be read and reviewed  that is review _before_ we about spending significant time toward implementation.

**Comment by chandadharap** [comment]
Taking over as Requirements. Breaking into stories with dev.

**Comment by chandadharap** [comment]
This has been broken down, only a placeholder.

**Comment by chandadharap** [comment]
old epic story. done.
