### ISSUE TITLE
Epic: Gateway Arc Implementation

### ISSUE THREAD

**Issue by altsang** [strongloop/strong-arc#1384]
As a SL Arc user, we want a GW module with the first view to handle the GW mapping use case, so that I can minimally configure my gateway with the built in policies for MVP.

UX specs folder: https://drive.google.com/drive/folders/0B1FTzkB7697GQWlPTDhfSFkyMnM
/cc: @stacy-hunt to update with the final UX export

## General Stories break up by Sean
- [x] wrap up prototype and story estimation

prototype: http://gateway1proto.herokuapp.com/#/
- [ ] integrate with LB API (dependency on api dev)
- [x] init Gateway Arc module (sep. branch, feature flag, port prototype code) 
- [ ] policy icons (stacy)
- [ ] landing page graphic (logo)(stacy)
- [ ] final visual design  (stacy)
- [ ] e2e test plan (outline what can/should be tested (ui interaction map)
- [ ] e2e tests (https://github.com/strongloop/strong-arc/issues/1419)
- [ ] context help (Arc / dox group) (https://github.com/strongloop-internal/scrum-loopback/issues/358)
- [ ] documentation (rand)

### mapping list
 - [ ]  story https://github.com/strongloop/strong-arc/issues/1396
- table cols:
- name (editable inline)
- verb (select)
- endpoint pattern (text)
- scopes (if pipeline has auth policy with scopes)
- pipeline (context modal)
- endpoint ( if pipeling has proxy policy

### mapping form
 - [ ]  story https://github.com/strongloop/strong-arc/issues/1397
- name - input
- verb - select dropdown (single)
- endpoint - input single value (could use some context help)
- pipeline 
-- select from list
-- link to add new (clone options)

### mapping pipeline chooser
 - [ ]  https://github.com/strongloop/strong-arc/issues/1398
- select list of available pipelines 
- button to create a new one (take you to pipeline editor view

### mapping detail view
 - [ ] story https://github.com/strongloop/strong-arc/issues/1400
- blow out the details 
- similar to ‘add new’ form
- base page
- mostly pipeline details

### pipeline context modal
 - [ ] story https://github.com/strongloop/strong-arc/issues/1401
- button to trigger the view
- slide out with table list of pipelines 

### pipeline list view
 - [ ]  story https://github.com/strongloop/strong-arc/issues/1403
- list of existing pipelines
- show policy summary cell

### policy summary cell
 - [ ]  https://github.com/strongloop/strong-arc/issues/1404
- list of associated policies
- context modal to show policy details
- order is important
- ‘edit’ command (warning will cause issues - do you want?

### pipeline detail 
- is this needed?

### pipeline form 
 - [ ]  story https://github.com/strongloop/strong-arc/issues/1405
- name
- policy editor 

### tree nav
 - [ ]  story https://github.com/strongloop/strong-arc/issues/1406
- top level entities
- child instances

### pipeline editor view
 - [ ]  story https://github.com/strongloop/strong-arc/issues/1407
- create new
- clone
- copy

### pipeline policy list table
 - [ ]  story https://github.com/strongloop/strong-arc/issues/1408
- read only list of pipeline policies
- in order
- with details for each type
- and icons
- command link to modify a policy (would trigger ‘new’ derivative pipeline) - see pipeline editor view

### policy list
 - [ ]  story https://github.com/strongloop/strong-arc/issues/1409
- list of policies
- name
- type
- values

### policy form
 - [ ] story  https://github.com/strongloop/strong-arc/issues/1410
- name
- dynamic fields based on type

### pipeline policy detail modal
 - [ ]  story https://github.com/strongloop/strong-arc/issues/1411
- policy name
- policy type
- show the relevant name/value pairs for policy

### pipeline policy editor 
 - [ ] story:  https://github.com/strongloop/strong-arc/issues/1412
- add remove policies
- change order
- links to modify/clone

connected to #1412

**Comment by seanbrookes** [comment]
First child - initial ui prototype https://github.com/strongloop-internal/scrum-nodeops/issues/751

**Comment by chandadharap** [comment]
Is the prototype to be continued in Sprint 74? Or does Stacy take it from here?
Or does this need to be broken down into separate implementation stories for Gateway mapping implementation?

**Comment by seanbrookes** [comment]
we should continue the prototype work until everyone agrees that the UX/UI works as expected.
some notes about the work as it falls out
- stacy and I should continue to cycle on the prototype/wireframes until the ux is hammered out (shouldn't take mre than a couple more cycles)
- we should be able to take a pretty confident inventory of ui components by tomorrow which should give us a good starting place for dividing up the work between Anthony and myself.
- still not clear on what the api is going to look like so there is some risk there but the mock backend driving the prototype should allow us to keep making progress
- will still need final visual design but there shouldn't be much risk there as we are mostly re-using existing patterns/styles

**Comment by seanbrookes** [comment]
High level list of views and components:

### mapping list
- table cols:
- name (editabled inline)
- verb (select)
- endpoint pattern (text)
- scopes (if pipeline has auth policy with scopes)
- pipeline (context modal)
- endpoint ( if pipeling has proxy policy

### mapping form
- name - input
- verb - select dropdown (single)
- endpoint - input single value (could use some context help)
- pipeline 
-- select from list
-- link to add new (clone options)

### mapping pipeline chooser
- select list of available pipelines 
- button to create a new one (take you to pipeline editor view

### mapping detail view
- blow out the details 
- similar to ‘add new’ form
- base page
- mostly pipeline details

### pipeline context modal
- button to trigger the view
- slide out with table list of pipelines 

### pipeline list view
- list of existing pipelines
- show policy summary cell

### policy summary cell
- list of associated policies
- context modal to show policy details
- order is important
- ‘edit’ command (warning will cause issues - do you want?

### pipeline detail 
- is this needed?

### pipeline form 
- name
- policy editor 

### tree nav
- top level entities
- child instances

### pipeline editor view
- create new
- clone
- copy

### pipeline policy list table
- read only list of pipeline policies
- in order
- with details for each type
- and icons
- command link to modify a policy (would trigger ‘new’ derivative pipeline) - see pipeline editor view

### policy list
- list of policies
- name
- type
- values

### policy form
- name
- dynamic fields based on type

### pipeline policy detail modal
- policy name
- policy type
- show the relevant name/value pairs for policy

### pipeline policy editor 
- add remove policies
- change order
- links to modify/clone

**Comment by chandadharap** [comment]
Just to be clear, this story is about spiking on the Epic using the UX prototype approach.

**Comment by seanbrookes** [comment]
this is the true 'Epic' for the Arc v1 implementation of Gateway.  All the child stories roll up to this one.
The 'spike' you refer to is: https://github.com/strongloop/strong-arc/issues/1416

**Comment by chandadharap** [comment]
I consider this done. So I'll close. Not sure how that affects your own tracking of the list? perhaps clone and add into backlog with an estimate of zero if you want to view in waffle, else you can continue to use the closed issue on github.

I'll look for these stories under Waffle Milestone for gateway.
