### ISSUE TITLE
rename a datasource or model property creates a clone

### ISSUE THREAD

**Issue by altsang** [strongloop/strong-arc#9]
Related: https://github.com/strongloop/loopback-workspace/issues/107

Operations to fix:
- [x] rename a model (see #92)
- [x] rename a datasource (see #103)
- [x] rename a property (see #103)
